slika1= imread('lenna.png');
%imshow(slika1);
slika2=rgb2gray(slika1);
%imshow(slika2);
slika3=255-slika2;
%imshow(slika3);
slika4=imbinarize(slika2, 0.4);
%imshow(slika4);
se=strel('line',5,45);
slika5=imerode(slika4,se);
%imshow(slika5);
slika6=imdilate(slika5,se);
%imshow(slika6);
h=fspecial('motion',20,45);
slika7=imfilter(slika2,h,'replicate');
%imshow(slika7);
h1 = fspecial('disk',10);
slika8 = imfilter(slika2, h1, 'replicate');
%imshow(slika8);
slika10 = edge(slika2);
%imshow(slika10);
